### ISSUE TITLE
Refactor: change home api endpoint 

### ISSUE THREAD

**Issue by Yamyam-code** [Strong-Potato/TripVote-FE#109]
## Description

api 명세서를 참고하여 msw 및 타입 수정

### Task

- [ ] api 엔드포인트 수정
- [ ] useEffect => react-query
- [ ] 타입 수정
- [x] 지도 핀 클릭 시 이벤트
