### ISSUE TITLE
Conf : add variables and library

### ISSUE THREAD

**Issue by HOOOO98** [Strong-Potato/TripVote-FE#12]
## Description
초기 설정에서 추가하지 못한, 혹은 수정된 변수를 추가하고, 사용해야 할 공용 라이브러리를 설치합니다.

### Task

- [ ] 기본 폰트 크기 62.5%
- [ ] svgr 라이브러리 설치, 설정 파일
- [ ] 추가 된 변수 색 지정
