### ISSUE TITLE
Feat : detail page last markup todo

### ISSUE THREAD

**Issue by JeongMin83** [Strong-Potato/TripVote-FE#124]
## Description

> 상세페이지 마지막 마크업 작업

### Task

- [x] [메인-타이틀] 찜, 공유하기 버튼
- [x] [메인-타이틀] 찜하기 토스트 뜨는 조건문
- [x] [메인-쇼츠 리뷰] 리뷰 전체보기
- [ ] [메인-슬라이더] 사진 확대 기능
- [x] [메인-ALL] 비로그인 모달

- [x] [미트볼] 찜, 공유하기 바텀시트 닫히게

- [x] [리뷰쓰기] 리뷰 취소 모달

- [x] [후보 등록 - 새 투표 생성] 비활성 상태 시각적 표현 
- [x] [후보 등록 - 투표리스트] 여행 스페이스 선택 후 "생성된 투표가 없습니다."

- [x] [hotfix] 전화번호 밑줄 없애기
- [x] [hotfix] 별점 개수 지우기
