### ISSUE TITLE
Feat : set MSW for browser & server

### ISSUE THREAD

**Issue by NamgungJongMin** [Strong-Potato/TripVote-FE#14]
## Description

브라우저 환경과 서버 환경에서의 mocking을 위한 초기 세팅.

### Task

- [x] base interceptor public에 생성
- [x] 브라우저 및 노드 환경에서 적용될 handler 파일 생성 및 템플릿 작성
- [x] worker 설정 및 등록
- [x] jest 테스트에 msw 적용을 위한 파일 생성 및 수정
