### ISSUE TITLE
Feat : create a candidate add function in Search place and Wish list

### ISSUE THREAD

**Issue by SKY-PEY** [Strong-Potato/TripVote-FE#145]
## Description
상원님이 만드신 장소가져오기, 찜리스트에 후보 추가 기능을 추가합니다.

### Task

- [ ] 장소 추가 기능
- [ ]  장소에 tagline 추가해서 같이 투표후보로 추가
- [ ] api 추가
- [ ] votememo 도메인과 구조 수정
