### ISSUE TITLE
Design: change a map pin in vote page

### ISSUE THREAD

**Issue by SKY-PEY** [Strong-Potato/TripVote-FE#153]
## Description

보트 지도 페이지에서 조건 별 맵핀 이미지 수정

### Task

- [ ] 투표전-> 기본 맵핀, 대or소
- [ ] 투표 후 -> 1-3순위는 숫자, 그 밑은 기본, 포커스되면 큰 사이즈
- [ ] 투표 동률 -> 높은 순위로 표현하기
- [ ] 결과보기 상태 -> recoil 사용
