### ISSUE TITLE
Feat: add exception logic

### ISSUE THREAD

**Issue by HOOOO98** [Strong-Potato/TripVote-FE#164]
## Description
사이드 바 추가 기능 구현

### Task
- [x] 날짜 (형식 변환)
- [x] getspaces 응답 데이터 확인하기
- [x] 새 여행 만들기 -> 만들어진 spaceId 이동
- [ ] 새 여행 만들기 15개 이상 -> 모달
