### ISSUE TITLE
Feat: connect alarm API

### ISSUE THREAD

**Issue by HOOOO98** [Strong-Potato/TripVote-FE#165]
## Description
알람 API , 종모양 상태 관리

### Task
- [ ] [알림] 메세지 GET Api
- [ ] [알림] 종 모양 배지 상태 관리 로직(알림배지)
- [x] [알림] 홈 화면 알림 연결
