### ISSUE TITLE
Feat : create pages about email signup

### ISSUE THREAD

**Issue by NamgungJongMin** [Strong-Potato/TripVote-FE#20]
## Description

이메일로 회원가입 플로우에 사용될 페이지들 생성

### Task

- [ ] 이메일 인증 페이지 / 비밀번호 validation 및 작성 페이지
- [ ] nodemailer 연동 및 key 발급
- [ ] (session)flow 단계를 기록하고 삭제하는 로직 작성
