### ISSUE TITLE
Feat : add components in trip page

### ISSUE THREAD

**Issue by JSH99** [Strong-Potato/TripVote-FE#286]
## Description
여행 스페이스 페이지 모달, 토스트 추가

### Task

- [ ] 캘린더 날짜 변경 모달
- [ ] 경로 최적화 토스트
- [ ] 지난 여행 비활성화
