### ISSUE TITLE
Refactor: apply web accessibility for screen reader

### ISSUE THREAD

**Issue by NamgungJongMin** [Strong-Potato/TripVote-FE#299]
## Description
스크린 리더 사용자를 위한 웹 접근성 확보

### Task

- [ ] 디자인적 요소인 이미지의 스크린 리더 무시 적용
- [ ] 페이지에 표시되지 않는 섹션 영역 디스크립션 추가
- [ ] 유저 인터렉션이 복잡한 부분 aria-label 통해 디스크립션 추가
