### ISSUE TITLE
Feat: add list slide

### ISSUE THREAD

**Issue by Yamyam-code** [Strong-Potato/TripVote-FE#33]
## Description

홈페이지의 목록들을 넘길 수 있는 슬라이드 기능 구현

### Task

- [x] 슬라이드 기능 구현
- [x] 진행 중인 투표가 없을 때 나오는 카드 반응형 패딩 적용
- [x] 각 페이지 url 연결
