### ISSUE TITLE
Feat: create detail page markup 2

### ISSUE THREAD

**Issue by JeongMin83** [Strong-Potato/TripVote-FE#56]
## Description

> 상세 페이지 마크업 2

### Task

- [ ] 미트볼 바텀 시트
- [ ] 리뷰 바텀 시트
- [ ] 후보 등록 바텀 시트
