### ISSUE TITLE
Feat: connect API

### ISSUE THREAD

**Issue by HOOOO98** [Strong-Potato/TripVote-FE#97]
## Description
추가된 API를 연결합니다.

### Task

- [ ] 사이드바 : get members/my-spaces
- [ ] 사이드바 : get members/my-info
- [ ] 사이드바 : post spaces/

추가 API : 여행스페이스 가입, 인코딩된 코드
